plugins:
  editorconfig:
    enabled: false
  tslint:
    enabled: false
  eslint:
    enabled: true
    channel: 'eslint-6'
    config:
      config: .eslintrc-cc.json
    extensions:
      - .es6
      - .js
      - .jsx
      - .ts
      - .tsx
      - .mjs
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - 'spec/'
  - '!spec/support/helpers'
  - 'config/'
  - 'db/'
  - 'docs/public'
  - 'features/'
  - '.circleci/'
  - '.github/'
  - '.storybook/'
  - '.vscode/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - 'Tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
