name: Feature CI

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: nodejs project information
        id: projectinfo
        uses: gregoranders/nodejs-project-info@v0.0.6
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: npm run build
        run: |
          npm run build
        env:
          CI: true
      - name: npm test
        run: |
          npm test
        env:
          CI: true
      - name: npm run e2e
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
          xvfb-run --auto-servernum -- bash -c "npm run e2e"
        env:
          HEADLESS: true
          GITHUB_BRANCH: ${{ github.ref }}
          GITHUB_COMMIT: ${{ github.sha }}
          PACKAGE_JSON: ${{ steps.projectinfo.outputs.context }}
      - name: archive e2e screenshots
        uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        with:
          name: Screenshots Feature ${{ matrix.os }} ${{ matrix.node-version }}
          path: e2e/screenshots
