name: Release CI

on:
  release:
    types:
      - edited

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: nodejs project information
        id: projectinfo
        uses: gregoranders/nodejs-project-info@v0.0.6
      - name: git config
        run: |
          cat .git/config
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: npm run build
        run: |
          npm run build
        env:
          CI: true
      - name: npm test
        run: |
          npm test
        env:
          CI: true
      - name: npm run e2e
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
          xvfb-run --auto-servernum -- bash -c "npm run e2e"
        env:
          HEADLESS: true
          GITHUB_BRANCH: ${{ github.ref }}
          GITHUB_COMMIT: ${{ github.sha }}
          PACKAGE_JSON: ${{ steps.projectinfo.outputs.context }}
      - name: archive e2e screenshots
        uses: actions/upload-artifact@v1
        with:
          name: Screenshots Release ${{ matrix.os }} ${{ matrix.node-version }}
          path: e2e/screenshots
      - name: update storybook docs
        run: |
          cat .git/config
          cd docs/public
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "Gregor Anders"
          git status
          git checkout master
          cd ../..
          cat .git/config
          npm run build-storybook
          cat .git/config
          cd docs/public
          git status
          git add -f .
          git commit -m "${{ steps.projectinfo.outputs.name }} - v${{ steps.projectinfo.outputs.version }}" .
          git push
        env:
          NODE_ENV: production
          GITHUB_BRANCH: ${{ github.ref }}
          GITHUB_COMMIT: ${{ github.sha }}
          PACKAGE_JSON: ${{ steps.projectinfo.outputs.context }}
